#!/bin/sh # the sbatch script
#SBATCH --nodes=1 # number of nodes
#SBATCH --cpus-per-task=16 
#SBATCH --time=2:00:00 # put time of reservation here
#SBATCH --mail-user=chrisfm@iastate.edu # user
#SBATCH --mail-type=begin # mail is sent when the job begins
#SBATCH --mail-type=end # mail is sent when the job ends.
#SBATCH --error=bowtie.%J.err # sends stderr to file  bowtie.%J.err
#SBATCH --output=bowtie.%J.out # sends stdout to file bowtie.%J.out

cd $SLURM_SUBMIT_DIR # changedir to SLURM_SUBMIT_DIR - i.e go to job submission directory



module load bowtie2 # Loading the bowtie2 aligner to build the index for the reference genome


bowtie2-build chr1.fasta,chr2.fasta,chr3.fasta,chr4.fasta,chr5.fasta,chr6.fasta,chr7.fasta,chr8.fasta,chr9.fasta,chr10.fasta,chrMt.fasta,chrPt.fasta,chrUNKNOWN.fasta ZmAGPV2
# Runing bowtie2-build to index the reference genome. Here the genome is provided as a set of fasta files, one for each
# chromosome. The final argument is the index name (ZmAGPV2)
