#!/bin/bash
#SBATCH --nodes=5
#SBATCH --cpus-per-task=16
#SBATCH --time=20:00:00
#SBATCH --mail-user=chrisfm@iastate.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --error=tophat.%J.err
#SBATCH --output=tophat.%J.out

module load tophat

sample_info=sample_summary_rev.txt

sample=($(cut -f 1 "$sample_info"))

for fastq in ${sample[@]}
do

	tophat -o $fastq --num-threads=80 --solexa-quals --no-novel-juncs --transcriptome-index=databases/ZmAGPV2_transc/ZmAGPV2 --transcriptome-max-hits=1 databases/ZmAGPV2 input_files/${fastq}_1.fastq.gz input_files/${fastq}_2.fastq.gz

done
