#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=20:00:00
#SBATCH --mail-user=chrisfm@iastate.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --error=htseq.%J.err
#SBATCH --output=htseq.%J.out

module load python/2.7.12

sample_info=sample_summary.txt

sample=($(cut -f 1 "$sample_info"))


for fastq in ${sample[@]}

do

htseq-count -f bam -r pos -s no -i Parent ${fastq}/accepted_hits.bam databases/ZmAGPV2.gff > ${fastq}_counts.txt

done



