#!/bin/sh

#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=4:00:00
#SBATCH --mail-user=chrisfm@iastate.edu
#SBATCH --mail-type=begin
#SBATCH --mail-type=end
#SBATCH --error=fastqc.%J.err
#SBATCH --output=fastqc.%J.out

module load fastqc # Load fastqc software

ls input_files/*.gz | xargs -P 16 -I xx fastqc -o fastqc_out xx
# List all the files that end in .gz inside the input_files folder then passes each of those file names as an argument to be
# used with fastq. The -o argument sets the output directory to fastqc_out.
# the xargs command with the -P 16 argument establish 16 parallel processes.